# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LSZ_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

# class comboExtent(QtWidgets.QComboBox):
#
# 	    def __init__(self, parentModule, parent=None):
# 	        super(comboExtent, self).__init__(parent)
# 	        self.iface = parentModule.iface
# 	        self.contextMapTool = selectExtentMapTool(self)
# 	        self.activated.connect(self.checkItem)
# 	        self.addItem("CANVAS EXTENT",'C')
# 	        parentModule.visibilityChanged.connect(self.visibilityChangedAction)
#
# 	    def visibilityChangedAction(self, visible):
# 	        if not visible:
# 	            self.contextMapTool.reset()
#
# 	    def showPopup(self):
#
# 	        self.clear()
#
# 	        self.addItem("CANVAS EXTENT",'C')
# 	        self.addItem("SELECT EXTENT ON CANVAS",'S')
#
# 	        for id,layer in QgsProject.instance().mapLayers().items():
# 	            self.addItem("%s [%s]" % (layer.name(),layer.crs().authid()), layer)
#
# 	        super(comboExtent, self).showPopup()
#
# 	    def currentExtent(self):
# 	        if self.currentData() == 'S':
# 	            return self.selectedExtent
# 	        elif self.currentData() == 'C':
# 	            return self.iface.mapCanvas().extent()
# 	        else:
# 	            return self.currentData().extent()
#
# 	    def checkItem(self):
# 	        self.contextMapTool.reset()
# 	        if self.currentData() == 'S':
# 	            self.iface.mapCanvas().setMapTool(self.contextMapTool)
#
#
# class selectExtentMapTool(QgsMapTool):
# 	def __init__(self, parentObj):
# 		self.parentObj = parentObj
# 		self.iface = parentObj.iface
# 		QgsMapTool.__init__(self, self.iface.mapCanvas())
# 		self.contextShape = QgsRubberBand(self.iface.mapCanvas(),QgsWkbTypes.LineGeometry )
# 		self.contextShape.setWidth( 1 )
# 		self.contextShape.setColor(QtCore.Qt.red)
# 		self.pressed = False

class Ui_WoEDialogBase(object):
    def setupUi(self, WoEDialogBase):
        WoEDialogBase.setObjectName("WoEDialogBase")
        WoEDialogBase.resize(723, 925)
        self.gridLayout = QtWidgets.QGridLayout(WoEDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(WoEDialogBase)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 689, 954))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 26, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 36, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 10, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 15, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 31, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_5.setDecimals(4)
        self.doubleSpinBox_5.setMaximum(1000000000.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_2.addWidget(self.doubleSpinBox_5, 31, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 32, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 11, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 9, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 19, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 9, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 4, 2, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_3.setMinimum(-100000000.0)
        self.doubleSpinBox_3.setMaximum(100000000.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_2.addWidget(self.doubleSpinBox_3, 20, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 15, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 8, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 4, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 21, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 6, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 5, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 5, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 9, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 22, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox.setMinimum(-100000000.0)
        self.doubleSpinBox.setMaximum(100000000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 22, 2, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 14, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 14, 3, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_4.setMinimum(-100000000.0)
        self.doubleSpinBox_4.setMaximum(100000000.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_2.addWidget(self.doubleSpinBox_4, 21, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 3, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 10, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 10, 3, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 36, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 36, 3, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 15, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 11, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 14, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 11, 0, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_6.setDecimals(4)
        self.doubleSpinBox_6.setMaximum(1000000000.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_2.addWidget(self.doubleSpinBox_6, 32, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 8, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 3, 2, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_2.addWidget(self.lineEdit_16, 16, 2, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_2.setMinimum(-100000000.0)
        self.doubleSpinBox_2.setMaximum(100000000.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 19, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 27, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 16, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 20, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 16, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 1, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 12, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 33, 2, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 26, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 25, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 26, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 17, 2, 1, 1)

		self.mExtentGroupBox = gui.QgsExtentGroupBox(self.scrollAreaWidgetContents)
        self.mExtentGroupBox.setObjectName("mExtentGroupBox")
		self.gridLayout_2.addWidget(self.mExtentGroupBox, 23, 2, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
		self.button_box = QtWidgets.QDialogButtonBox(WoEDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 1, 0, 1, 1)

        self.retranslateUi(WoEDialogBase)
        self.button_box.accepted.connect(WoEDialogBase.accept)
        self.button_box.rejected.connect(WoEDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(WoEDialogBase)

    def retranslateUi(self, WoEDialogBase):
        _translate = QtCore.QCoreApplication.translate
        WoEDialogBase.setWindowTitle(_translate("WoEDialogBase", "WoEmodel"))
        self.pushButton_13.setText(_translate("WoEDialogBase", "..."))
        self.label_5.setText(_translate("WoEDialogBase", "Output file (.tif)"))
        self.label_8.setText(_translate("WoEDialogBase", "Cause 3 classes (optional)"))
        self.label_4.setText(_translate("WoEDialogBase", "Cause 4 (optional)"))
        self.label_11.setText(_translate("WoEDialogBase", "DEM (map of reference)"))
        self.label_6.setText(_translate("WoEDialogBase", "Cause 1 classes"))
        self.label_16.setText(_translate("WoEDialogBase", "width"))
        self.label.setText(_translate("WoEDialogBase", "Cause 1"))
        self.label_17.setText(_translate("WoEDialogBase", "height"))
        self.label_2.setText(_translate("WoEDialogBase", "Cause 2 (optional)"))
        self.label_14.setText(_translate("WoEDialogBase", "xmin"))
        self.pushButton_7.setText(_translate("WoEDialogBase", "..."))
        self.pushButton_11.setText(_translate("WoEDialogBase", "..."))
        self.pushButton_3.setText(_translate("WoEDialogBase", "..."))
        self.label_13.setText(_translate("WoEDialogBase", "ymin"))
        self.label_21.setText(_translate("WoEDialogBase", "Classification of the causative factors (.txt):"))
        self.pushButton.setText(_translate("WoEDialogBase", "..."))
        self.pushButton_4.setText(_translate("WoEDialogBase", "..."))
        self.label_7.setText(_translate("WoEDialogBase", "Cause 2 classes (optional)"))
        self.label_12.setText(_translate("WoEDialogBase", "ymax"))
        self.pushButton_10.setText(_translate("WoEDialogBase", "..."))
        self.pushButton_2.setText(_translate("WoEDialogBase", "..."))
        self.pushButton_8.setText(_translate("WoEDialogBase", "..."))
        self.pushButton_5.setText(_translate("WoEDialogBase", "..."))
        self.pushButton_9.setText(_translate("WoEDialogBase", "..."))
        self.label_10.setText(_translate("WoEDialogBase", "Landslide inventory (.shp)"))
        self.label_9.setText(_translate("WoEDialogBase", "Cause 4 classes (optional)"))
        self.pushButton_6.setText(_translate("WoEDialogBase", "..."))
        self.label_3.setText(_translate("WoEDialogBase", "Cause 3 (optional)"))
        self.label_23.setText(_translate("WoEDialogBase", "Cells size as map unite"))
        self.label_18.setText(_translate("WoEDialogBase", "Work folder (optional)"))
        self.label_15.setText(_translate("WoEDialogBase", "xmax"))
        self.pushButton_12.setText(_translate("WoEDialogBase", "..."))
        self.label_20.setText(_translate("WoEDialogBase", "Causative factors:"))
        self.label_22.setText(_translate("WoEDialogBase", "Working variables:"))
        self.label_24.setText(_translate("WoEDialogBase", "Output layer"))
        self.label_25.setText(_translate("WoEDialogBase", "Boundary of the area of interest:"))
        self.label_26.setText(_translate("WoEDialogBase", "Polygon (.shp)(optional)"))
        self.label_19.setText(_translate("WoEDialogBase", "Extension of the study area:"))

from qgis import gui

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WoEDialogBase = QtWidgets.QDialog()
    ui = Ui_WoEDialogBase()
    ui.setupUi(WoEDialogBase)
    WoEDialogBase.show()
    sys.exit(app.exec_())
